import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { NavigationMenuMain } from "@/components/landing/navbar"; // Adjust the path as necessary
import Image from "next/image";
import app_logo from "../../public/app-logo.png";
import { SignedIn, UserButton } from "@clerk/nextjs";
import FooterSection from "@/components/landing/footer";
import { Coins } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-11/12 overflow-x-hidden mx-auto `}
        >
          <div className=" p-2 flex  items-center w-full font-bold text-lg border-b text-gray-800 justify-between ">
            <div className="flex items-center gap-2">
              <Image src={app_logo} alt="logo" width={70} height={70} />
              Appify PWC
            </div>
            <div className="flex gap-5">
              <div className="flex items-center p-2 bg-green-100 rounded-md">
                <Coins className=" text-2xl mr-2" />
                <span className="text-base font-semibold">245 Points</span>
              </div>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </div>

          <div className="p-4 flex items-center justify-center">
            <NavigationMenuMain />
          </div>
          {children}
          <FooterSection />
        </body>
      </html>
    </ClerkProvider>
  );
}
